import type { Actor, Message, Project, Turn } from '../types';
import type { OpenIssue } from '../live';
import { AVATARS, HISTORY, type RepoEvent } from './history';

/**
 * Slide 4's replay: every issue, PR, and merge in this repo (see history.ts,
 * regenerated by scripts/gen-demo-history.mjs), streamed through the real
 * workspace shell as fast as legibility allows.
 */

function hue(id: string): number {
  let h = 0;
  for (let i = 0; i < id.length; i++) h = (h * 31 + id.charCodeAt(i)) % 360;
  return h;
}

export const TL_ACTORS: Record<string, Actor> = {};
for (const event of HISTORY) {
  if (TL_ACTORS[event.author]) continue;
  const avatarUrl = AVATARS[event.author];
  TL_ACTORS[event.author] = event.author.endsWith('[bot]')
    ? event.author.startsWith('particle')
      ? { kind: 'app', id: event.author, name: 'particle' } // keeps the particle mark
      : {
          kind: 'agent',
          id: event.author,
          name: event.author.replace('[bot]', ''),
          role: 'reviewer',
          avatarUrl,
        }
    : {
        kind: 'human',
        id: event.author,
        name: event.author,
        handle: event.author,
        hue: hue(event.author),
        avatarUrl,
        online: true,
      };
}

const REPO_URL = 'https://github.com/supernovas/particle';

const WHEN = new Intl.DateTimeFormat('en-US', {
  timeZone: 'America/Los_Angeles',
  month: 'short',
  day: 'numeric',
  hour: 'numeric',
  minute: '2-digit',
});

/** "Aug 23 · 1:06 PM" (PST) */
export function when(iso: string): string {
  return WHEN.format(new Date(iso)).replace(', ', ' · ');
}

function line(event: RepoEvent): string {
  switch (event.kind) {
    case 'issue':
      return event.body
        ? `#${event.number} opened — ${event.title}\n“${event.body}”`
        : `#${event.number} opened — ${event.title}`;
    case 'pr':
      return `PR #${event.number} — ${event.title}`;
    case 'merge':
      return `merged #${event.number} — ${event.title}`;
    case 'comment':
      return `on #${event.number} — “${event.body}”`;
  }
}

function captionLine(event: RepoEvent): string {
  switch (event.kind) {
    case 'comment':
      return `${event.author} on #${event.number}`;
    case 'merge':
      return `merged #${event.number} — ${event.title}`;
    default:
      return `#${event.number} — ${event.title}`;
  }
}

export interface TimelapseState {
  messages: Message[];
  projects: Project[];
  issues: OpenIssue[];
  turns: Turn[];
  caption: string;
  done: boolean;
}

export const TOTAL = HISTORY.length;

const HUMANS = new Set(HISTORY.filter((e) => !e.author.endsWith('[bot]')).map((e) => e.author));

/** Workspace state after the first `count` repo events. */
export function timelapseState(count: number): TimelapseState {
  const shown = HISTORY.slice(0, Math.min(count, TOTAL));
  const messages: Message[] = shown.map((event, i) => ({
    id: `h${i}`,
    channelId: 'github-issues',
    authorId: event.author,
    time: when(event.at),
    text: line(event),
    kind: event.kind,
    projectId: event.number === 1 && event.kind === 'issue' ? 'bootstrap' : undefined,
  }));
  const issues: OpenIssue[] = shown
    .filter((e) => e.kind === 'issue')
    .map((e) => ({ number: e.number, title: e.title, url: `${REPO_URL}/issues/${e.number}` }));
  const merges = shown.filter((e) => e.kind === 'merge').length;
  const done = count >= TOTAL;

  // The right pane follows the founding thread: everything on issue #1.
  const turns: Turn[] = shown
    .filter((e) => e.number === 1)
    .map((e, i) => ({
      id: `t${i}`,
      projectId: 'bootstrap',
      actorId: e.author,
      kind: 'comment' as const,
      time: when(e.at),
      title: e.body || e.title,
    }));

  const projects: Project[] =
    shown.length === 0
      ? []
      : [
          {
            id: 'bootstrap',
            title: 'Bootstrap Particle',
            ref: '',
            channelId: 'github-issues',
            status: done ? 'converged' : merges > 0 ? 'executing' : 'open',
            startedBy: HISTORY[0]!.author,
            issue: 1,
            round: Math.max(1, merges),
            tasks: [],
            diff: { files: 0, additions: 0, deletions: 0 },
            watchers: [...HUMANS],
          },
        ];

  const last = shown.at(-1);
  const caption = done
    ? `${TOTAL} updates · one day · 2 humans and a fleet of agents`
    : last
      ? `${shown.length}/${TOTAL} · ${captionLine(last)}`
      : 'day zero';

  return { messages, projects, issues, turns, caption, done };
}
